import { camelCase, printValue, prune } from "./print";

/**
 * Content-file generation for builder saves.
 * - One file per content key: src/config/content/<key>.ts
 * - Plus a regenerated src/config/content/index.ts wiring every key.
 * Generated files are untyped exports — content is validated against each
 * section's Zod schema at build time (and again by the save route), so the
 * type annotation would be redundant.
 */

/** Keys whose content is derived at build time, never written as files. */
export const DERIVED_CONTENT_KEYS = new Set(["case-studies"]);

export function serializeContentFile(key: string, value: unknown): string {
  const exportName = camelCase(key);
  return `/**
 * Generated by /builder — hand-edits are fine, the builder reads them back.
 * Validated against the "${key}" section's schema at build time.
 */
export const ${exportName} = ${printValue(prune(value), "")};
`;
}

/** Regenerates content/index.ts from the full set of content keys. */
export function serializeContentIndex(keys: string[]): string {
  const fileKeys = [...new Set(keys)]
    .filter((key) => !DERIVED_CONTENT_KEYS.has(key))
    .sort();

  const imports = fileKeys
    .map((key) => `import { ${camelCase(key)} } from "./${key}";`)
    .join("\n");

  const mapEntries = fileKeys
    .map((key) =>
      key === camelCase(key)
        ? `  ${key},`
        : `  "${key}": ${camelCase(key)},`,
    )
    .join("\n");

  return `import type { ContentMap } from "@/folio/core/types";
import type { CaseStudiesContent } from "@/folio/sections/case-studies/schema";
import { getCaseStudies } from "@/folio/content/mdx";
${imports}

/** Case-study cards derive from the MDX files in /content/case-studies. */
const caseStudies: CaseStudiesContent = {
  heading: "Case Studies",
  kicker: "The long versions",
  items: getCaseStudies().map((entry) => ({
    title: entry.frontmatter.title,
    summary: entry.frontmatter.summary,
    slug: entry.slug,
    client: entry.frontmatter.client,
    date: entry.frontmatter.date,
    tags: entry.frontmatter.tags,
    cover: entry.frontmatter.cover,
  })),
};

/**
 * Section content, keyed by section id (or by a SectionConfig.content key if
 * one section renders twice with different data). Each entry is validated
 * against its section's schema at build time.
 */
export const content: ContentMap = {
${mapEntries}
  "case-studies": caseStudies,
};
`;
}
