import type { SiteConfig } from "@/folio/core/types";
import type { BuilderSavePayload } from "./types";

import { printValue, prune } from "./print";

/**
 * Builder payload → src/config/site.config.ts source text. Printer shared
 * with serialize-content (see ./print.ts) so all generated files format
 * identically.
 */

/** Assembles the full SiteConfig object the payload represents. */
export function payloadToConfig(payload: BuilderSavePayload): SiteConfig {
  const { state, passthrough } = payload;
  return {
    profile: passthrough.profile,
    theme: state.theme,
    mode: state.mode,
    colors: state.colors,
    modules: passthrough.modules?.length ? passthrough.modules : undefined,
    sections: state.sections.map((entry) => ({
      id: entry.id,
      variant: entry.variant,
      motion: entry.motion,
      enabled: entry.enabled ? undefined : false,
    })),
    motion: {
      intensity: state.intensity,
      respectReducedMotion: passthrough.respectReducedMotion,
    },
  } as SiteConfig;
}

export function serializeConfig(payload: BuilderSavePayload): string {
  const config = prune(payloadToConfig(payload));
  return `import { defineConfig } from "@/folio/core/define";

/**
 * Generated by /builder — hand-edits are fine, the builder reads them back.
 * colors: primary/secondary/tertiary/background/foreground/muted/border/card,
 * top-level = both modes, light:{}/dark:{} refine one mode.
 */
export default defineConfig(${printValue(config, "")});
`;
}
